_Core:
  resource:
    path: ../src/_Core/Controller/
    namespace: App\_Core\Controller
  type: attribute
Application:
  resource:
    path: ../src/Application/Controller/
    namespace: App\Application\Controller
  type: attribute
Auth:
  resource:
    path: ../src/Auth/Controller/
    namespace: App\Auth\Controller
  type: attribute