parameters:

imports:
  - { resource: '../vendor/cloudbase/latte-helper/config/services.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'

  App\Application\Controller\:
    resource: '../src/Application/Controller'
    tags: [ 'controller.service_arguments' ]
    calls:
      - method: setLatteFactory
        arguments:
          - '@CloudBase\LatteHelper\Classes\Latte\LatteEngineFactory'

  App\Auth\Controller\:
    resource: '../src/Auth/Controller'
    tags: [ 'controller.service_arguments' ]
    calls:
      - method: setLatteFactory
        arguments:
          - '@CloudBase\LatteHelper\Classes\Latte\LatteEngineFactory'
